### ISSUE TITLE
don’t commit node_modules folder

### ISSUE THREAD

**Issue by gr2m** [sohini-roy/github-set-pr-status#1]
usually you don’t want to commit the `node_modules` folder to your git repository. To prevent that from happening, create a `.gitignore` file with the line `node_modules` in it.

After that, run `git rm -r node_modules` to remove the node_modules folder from git tracking. You will need to run `npm install` afterwards as the folder also gets deleted that way.

Feel free to send pull requests and ping me in them if you want me to do a review :)

**Comment by Alice-anjali** [comment]
Issue fixed
