### ISSUE TITLE
Resolve Authentication using github token

### ISSUE THREAD

**Issue by sohini-roy** [sohini-roy/github-set-pr-status#3]
![screenshot from 2017-07-19 23-59-21](https://user-images.githubusercontent.com/16969415/28383533-1739174a-6cdf-11e7-8f91-426f2633894c.png)

We are using "node-github" package. Have a look at : https://www.npmjs.com/package/node-github
To specify scopes, we have to specify them using : https://mikedeboer.github.io/node-github/#api-authorization-getOrCreateAuthorizationForApp
As mentioned there we have to create a client_secret through Google Cloud platform. Have a look at :
https://developers.google.com/adwords/api/docs/guides/authentication#webapp (i know, we are working on a CLI app not a web app but there isn't any client_secret for them).
The problem is probably in line:84 as we never enter the function described in line:87. As a result of which "Authenticating you, please wait..." runs infinitely.
Thanks for having a look :)

**Comment by gr2m** [comment]
when I try to run `node index.js` it fails with `Error: Cannot find module './config'`. Did you push the latest version of your code to GitHub?

**Comment by sohini-roy** [comment]
it is in .gitignore. it contains github-token. Create a config.json file, in it a "githubToken" key which will contain your token and put your token in it.
Sorry that I didn't update my README.md to it.

**Comment by gr2m** [comment]
Got it 👍 

For configuration I can recommend the [dotenv](https://www.npmjs.com/package/dotenv) package, check it out :)

As this is a CLI tool that people might want to install globally I’d suggest that you allow to pass the token as argument or set it as environment variable instead of having a configuration file

**Comment by gr2m** [comment]
When you have the GitHub token, you don’t need to ask for the username anymore, you can catch it from the API (https://developer.github.com/v3/users/#get-the-authenticated-user) or using the github library it’s `github.users.get()`

**Comment by gr2m** [comment]
ah wait you ask it so you get the repository owner, right? Maybe it would be simpler to just enter the full pull request URL and then the code can extract the information out of that it needs?

**Comment by gr2m** [comment]
you are using the wrong npm package. I know it’s confusing, but the npm package is called [github](https://www.npmjs.com/package/github), note node-github

**Comment by gr2m** [comment]
look what I just did with your tool :)

![image](https://user-images.githubusercontent.com/39992/28402501-08224e3e-6cd5-11e7-8c31-689236229ee8.png)

You are close! A few more things you’ll need to fix, but not much left

**Comment by sohini-roy** [comment]
Thanks a lot for helping. This issue has been resolved :)
